MvcEntityFramework/Controllers/EmpleadosHospitalController.cs
using Microsoft.AspNetCore.Mvc;
using MvcEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcEntityFramework.Controllers
{
    public class EmpleadosHospitalController : Controller
    {
        RepositoryEmpleadosHospital repo;
        public EmpleadosHospitalController(RepositoryEmpleadosHospital repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            return View(this.repo.GetEmpleadoHospital());
        }
        
        public IActionResult ProcedimientoEmpleado()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ProcedimientoEmpleado(int hospitalcod)
        {
            return View(this.repo.GetEmpleadosHospital(hospitalcod));
        }
    }
}

MvcEntityFramework/Views/EmpleadosHospital/Index.cshtml
@model List<EmpleadoHospital>

@Html.ActionLink("Procedimiento", "ProcedimientoEmpleado", "EmpleadosHospital", null, new { @class="btn btn-success my-4"})

<table class="table text-white table-dark my-5">
    <thead>
        <tr>
            <th>Numero empleado</th>
            <th>Apellido</th>
            <th>Funcion</th>
            <th>Salario</th>
            <th>Codigo Hospital</th>
        </tr>
    </thead>
    <tbody>
        @foreach (EmpleadoHospital eh in Model)
        {
            <tr>
                <td>@eh.IdEmpleado</td>
                <td>@eh.Apellido</td>
                <td>@eh.Funcion</td>
                <td>@eh.Salario</td>
                <td>@eh.HospitalCod</td>
            </tr>
        }
    </tbody>
</table>

MvcEntityFramework/Views/EmpleadosHospital/ProcedimientoEmpleado.cshtml
@model ProcedimientoEmpleadoHospital

<form method="post">
    <label>Codigo Hospital</label>
    <input class="form-control" type="text" name="hospitalcod"/>
    <button type="submit" class="btn btn-info my-5">
        buscar
    </button>
</form>
@if(Model != null)
{
    <h2>Suma salarial: @Model.SumaSalarial</h2>
    <h2>Media Salarial: @Model.MediaSalarial</h2>
    <table class="table table-dark text-white">
        <thead>
            <tr>
                <th>Apellido</th>
                <th>Funcion</th>
                <th>Salario</th>
            </tr>
        </thead>
        <tbody>
            @foreach (EmpleadoHospital p in Model.Empleados)
            {
                <tr>
                    <td>@p.Apellido</td>
                    <td>@p.Funcion</td>
                    <td>@p.Salario</td>
                </tr>
            }
        </tbody>

    </table>
}