MvcEntityFramework/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using MvcEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcEntityFramework.Controllers
{

    public class DoctorController : Controller
    {
        RepositoryDoctor repo;
        public DoctorController(RepositoryDoctor repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            return View(this.repo.FinfAll());
        }
 
        [HttpPost]
        public IActionResult Index(int id, String especialidad)
        {
            this.repo.UpdateEspacialidad(id, especialidad);

            return RedirectToAction("index");
        }
        public IActionResult AumentarSalario()
        {
            ViewBag.especialidades = new List<String>(this.repo.Especialidades().ToList());
            
            return View(this.repo.FinfAll());
        }
        [HttpPost]
        public IActionResult AumentarSalario(int aumento, String especialidad)
        {

            this.repo.AumentarSalario(aumento, especialidad);
            ViewBag.especialidades = new List<String>(this.repo.Especialidades().ToList());

            return View(this.repo.DoctoresEspecialidad(especialidad));
        }
    }
}

MvcEntityFramework/Controllers/EnfermoController.cs
using Microsoft.AspNetCore.Mvc;
using MvcEntityFramework.Models;
using MvcEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcEntityFramework.Controllers
{
    public class EnfermoController : Controller
    {
       private RepositoryEnfermo context;

        public EnfermoController(RepositoryEnfermo context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.context.FindAll();
            return View(enfermos);
        }
        public IActionResult Detalle(int id)
        {
            Enfermo enfermo=  this.context.FindByInscription(id);

            return View(enfermo);
        }
        public IActionResult EnfermosGenero(String? genero)
        {
            List<Genero> generos = this.context.Sexos();
            ViewBag.sexos = generos;

            if(genero != null)
            {
                List<Enfermo> enfermos = this.context.FindEnfermoBySexo(genero);

                return View(enfermos);
            }

            return View();
        }
        public IActionResult Eliminar(int id)
        {
            this.context.Delete(id);

            return RedirectToAction("Index");
        }
        public IActionResult Insert()
        {
           List<Genero> generos= this.context.Sexos();
            return View(generos);
        }
        [HttpPost]
        public IActionResult Insert(Enfermo enfermo)
        {
            this.context.Insert(enfermo);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            Enfermo enfermo= this.context.FindByInscription(id);
            List<Genero> generos = this.context.Sexos();
            ViewBag.generos = generos;
            return View(enfermo);
        }
        [HttpPost]
        public IActionResult Update(Enfermo enfermo)
        {
            this.context.Update(enfermo);
            return RedirectToAction("index");
        }
    }
}

MvcEntityFramework/Controllers/HospitalController.cs
using Microsoft.AspNetCore.Mvc;
using MvcEntityFramework.Models;
using MvcEntityFramework.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcEntityFramework.Controllers
{
    public class HospitalController : Controller
    {
        private RepositoryHospital repository;
        public HospitalController(RepositoryHospital repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            List<Hospital> hospitales = this.repository.findAll();
            return View(hospitales);
        }
    }
}

MvcEntityFramework/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <meta name="theme-color" content="#7952b3">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }
    </style>

    <!-- Custom styles for this template -->
    <link href="~/css/cover.css" rel="stylesheet" />
</head>
<body class="d-flex h-100 text-center text-white bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">Cover</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    @Html.ActionLink("Coches", "Index", "coches", null, new { @class = "nav-link" })
                    @Html.ActionLink("Departamentos", "Index", "departamentos", null, new { @class = "nav-link" })
                    @Html.ActionLink("Hospitales", "Index", "Hospital", null, new { @class = "nav-link" })
                    @Html.ActionLink("Enfermos", "Index", "Enfermo", null, new { @class = "nav-link" })
                    @Html.ActionLink("Empleados", "Index", "Empleados", null, new { @class = "nav-link" })
                    @Html.ActionLink("Empleados Lambda", "EmpleadosDepartamentoLambda", "Empleados", null, new { @class = "nav-link" })
                    @Html.ActionLink("Plantilla", "Index", "Plantilla", null, new { @class = "nav-link" })
                    @Html.ActionLink("Doctores", "Index", "Doctor", null, new { @class = "nav-link" })
                    @Html.ActionLink("Empleados Hopsital", "Index", "EmpleadosHospital", null, new { @class = "nav-link" })
                    @Html.ActionLink("Empleados Vista", "Index", "EmpleadosVista", null, new { @class = "nav-link" })
                </nav>
            </div>
        </header>

        <main class="px-3">

           @RenderBody()

        </main>

        <footer class="mt-auto text-white-50">
            <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white"></a>.</p>
        </footer>
    </div>


    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/popper.min.js"></script>

    @RenderSection("scripts", false)
    
</body>

</html>